services:
  postgresql_test:
    image: postgres:18.4
    restart: always
    env_file: .env.test
    ports:
      - 6012:5432

  mongo_test:
    image: mongo:8.3.4
    restart: always
    env_file: .env.test
    ports:
      - 6022:27017
